version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - task
  - dependencies
  - backlog-dependencies
  ignore:
  - dependency-name: responses
    versions:
    - 0.13.2
  - dependency-name: setuptools
    versions:
    - 54.2.0
